version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - BACKEND_API_URL=http://backend:8080
    command: npm run dev
